version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/url-shortener
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
